### ISSUE TITLE
Tracking user-defined functions that do not create targets

### ISSUE THREAD

**Issue by arnold-c** [wlandau/targets#260]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

I'm hoping to try and track changes to user-defined functions do not create targets, but are used in a notebook that is part of a pipeline. For example, I have a quick plotting function that I use repeatedly, but I do not want to have to create a target for every single plot in a notebook as this would clutter the `_target.R` file. However, if I made a change to that function, even if it is sourced into the notebook, the pipeline thinks it is up to date. 

I believe this is different to issues #241 and #239 as these relate to packages, not standalone functions.

One thought I had was to write these functions in a separate R file that I can track using `format = "file"` like below, and this seems to work, but I just wanted to make sure this is a reasonable thing to do and wouldn't lead to unintended consequences.

In `_targets.R`:
```r
list(
    ...
    tar_target(
        user_functions,
        here::here("funs", "user-defined-functions.R")
        ),
        format = "file",
    ...
    tar_render(analysis_notebook, "analysis-notebook.Rmd")
    )
```

In my `user-defined-functions.R` file:
```r
library(tidyverse)

df <- tibble(thresholds = 0:10, sensitivity = seq(0, 1, 0.1), specificity = rev(seq(0, 1, 0.1)))

my_function <- function(data){
  data %>%
    pivot_longer(cols = sensitivity:specificity, names_to = "metric", values_to = "value") %>%
    ggplot(aes(x = thresholds, y = value, color = metric)) +
    geom_point()
}

threshold_metric_plot(data = df)
```

In my `Rmd` notebook:
```r
tar_load(user_functions)

my_function(data = df)
```

_Created on 2021-01-06 by the reprex package (v0.3.0)_

**Comment by wlandau** [comment]
> One thought I had was to write these functions in a separate R file that I can track using format = "file" like below, and this seems to work, but I just wanted to make sure this is a reasonable thing to do and wouldn't lead to unintended consequences.

Sounds like a great workaround to me.

Another approach is to define a target for all the function objects:

```r
tar_target(functions, list(my_function, fun2, fun3, ...))
```

This technique is less trigger-happy than `format = "file"` because it does not invalidate the target if there are trivial changes to comments and whitespace. For a function in memory, `targets` cannot tell the difference between this:

```r
my_function <- function(data){
  data %>%
    pivot_longer(cols = sensitivity:specificity, names_to = "metric", values_to = "value") %>%
    ggplot(aes(x = thresholds, y = value, color = metric)) +
    geom_point()
}
```

and this:

```r
my_function <- function(data){
  data %>%

    pivot_longer(
      cols = sensitivity:specificity,
      names_to = "metric",
      values_to = "value"
    ) %>%

    ggplot(aes(x = thresholds, y = value, color = metric)) +

    geom_point()
}
```
